name = "AppliSales"
uuid = "c1345d04-1a7a-4e7a-b935-9916dcf58fca"
authors = ["Rob Bontekoe"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
